### ISSUE TITLE
no copyright statement

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/uuid#3]
Please add copyright statement to README. Perhaps something like

    Copyright 2014-2015 HashiCorp

Thanks.

**Comment by sethvargo** [comment]
Hi @onlyjob 

Thank you for opening an issue. The LICENSE file contained at the root of the repo contains the rights and privileges that we grant to you. All projects under the "hashicorp" GitHub organization are copyrighted to HashiCorp or their respective authors. Thanks! :smile:

**Comment by onlyjob** [comment]
Please note that grant of license (or full text of the license) is not the same as copyright statement.

> All projects under the "hashicorp" GitHub organization are copyrighted to HashiCorp or their respective authors.

I believe it should be documented no matter how obvious it may appear to you.

  https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html
