### ISSUE TITLE
Not following RFC 4122

### ISSUE THREAD

**Issue by steko** [hashicorp/uuid#4]
If I understand correctly, the UUID implementation of this package is not compliant with [RFC 4122](https://tools.ietf.org/html/rfc4122).

Version 4 UUIDs have the form `xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx` where `x` is any hexadecimal digit and `y` is one of 8, 9, A, or B (e.g., `f47ac10b-58cc-4372-a567-0e02b2c3d479`).

I'm not implying that this implementation is bad or needs to be fixed :smile:  just that UUID generally refers to RFC 4122 compliant generators. If that's not the case, it could be clearly stated in the README.

**Comment by jefferai** [comment]
Hi there,

The readme does specify that the generated UUIDs use purely random bytes. This is explicitly not the behavior of the RFC and as such there is no claim of compliance.

Thanks!
